// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newConfession(db *gorm.DB, opts ...gen.DOOption) confession {
	_confession := confession{}

	_confession.confessionDo.UseDB(db, opts...)
	_confession.confessionDo.UseModel(&model.Confession{})

	tableName := _confession.confessionDo.TableName()
	_confession.ALL = field.NewAsterisk(tableName)
	_confession.ID = field.NewInt64(tableName, "id")
	_confession.UserID = field.NewInt64(tableName, "user_id")
	_confession.Name = field.NewString(tableName, "name")
	_confession.Content = field.NewString(tableName, "content")
	_confession.ImageUrls = field.NewString(tableName, "image_urls")
	_confession.IsAnonymous = field.NewInt8(tableName, "is_anonymous")
	_confession.IsVisible = field.NewInt8(tableName, "is_visible")
	_confession.CreatedAt = field.NewTime(tableName, "created_at")
	_confession.UpdatedAt = field.NewTime(tableName, "updated_at")
	_confession.DeletedAt = field.NewField(tableName, "deleted_at")

	_confession.fillFieldMap()

	return _confession
}

type confession struct {
	confessionDo confessionDo

	ALL         field.Asterisk
	ID          field.Int64  // 帖子ID
	UserID      field.Int64  // 用户ID
	Name        field.String // 昵称
	Content     field.String // 内容
	ImageUrls   field.String // 图片路径
	IsAnonymous field.Int8   // 匿名
	IsVisible   field.Int8   // 可见性
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 修改时间
	DeletedAt   field.Field  // 删除时间(软删除)

	fieldMap map[string]field.Expr
}

func (c confession) Table(newTableName string) *confession {
	c.confessionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c confession) As(alias string) *confession {
	c.confessionDo.DO = *(c.confessionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *confession) updateTableName(table string) *confession {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.UserID = field.NewInt64(table, "user_id")
	c.Name = field.NewString(table, "name")
	c.Content = field.NewString(table, "content")
	c.ImageUrls = field.NewString(table, "image_urls")
	c.IsAnonymous = field.NewInt8(table, "is_anonymous")
	c.IsVisible = field.NewInt8(table, "is_visible")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *confession) WithContext(ctx context.Context) IConfessionDo {
	return c.confessionDo.WithContext(ctx)
}

func (c confession) TableName() string { return c.confessionDo.TableName() }

func (c confession) Alias() string { return c.confessionDo.Alias() }

func (c confession) Columns(cols ...field.Expr) gen.Columns { return c.confessionDo.Columns(cols...) }

func (c *confession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *confession) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 10)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["name"] = c.Name
	c.fieldMap["content"] = c.Content
	c.fieldMap["image_urls"] = c.ImageUrls
	c.fieldMap["is_anonymous"] = c.IsAnonymous
	c.fieldMap["is_visible"] = c.IsVisible
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c confession) clone(db *gorm.DB) confession {
	c.confessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c confession) replaceDB(db *gorm.DB) confession {
	c.confessionDo.ReplaceDB(db)
	return c
}

type confessionDo struct{ gen.DO }

type IConfessionDo interface {
	gen.SubQuery
	Debug() IConfessionDo
	WithContext(ctx context.Context) IConfessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConfessionDo
	WriteDB() IConfessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConfessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConfessionDo
	Not(conds ...gen.Condition) IConfessionDo
	Or(conds ...gen.Condition) IConfessionDo
	Select(conds ...field.Expr) IConfessionDo
	Where(conds ...gen.Condition) IConfessionDo
	Order(conds ...field.Expr) IConfessionDo
	Distinct(cols ...field.Expr) IConfessionDo
	Omit(cols ...field.Expr) IConfessionDo
	Join(table schema.Tabler, on ...field.Expr) IConfessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConfessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConfessionDo
	Group(cols ...field.Expr) IConfessionDo
	Having(conds ...gen.Condition) IConfessionDo
	Limit(limit int) IConfessionDo
	Offset(offset int) IConfessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConfessionDo
	Unscoped() IConfessionDo
	Create(values ...*model.Confession) error
	CreateInBatches(values []*model.Confession, batchSize int) error
	Save(values ...*model.Confession) error
	First() (*model.Confession, error)
	Take() (*model.Confession, error)
	Last() (*model.Confession, error)
	Find() ([]*model.Confession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Confession, err error)
	FindInBatches(result *[]*model.Confession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Confession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConfessionDo
	Assign(attrs ...field.AssignExpr) IConfessionDo
	Joins(fields ...field.RelationField) IConfessionDo
	Preload(fields ...field.RelationField) IConfessionDo
	FirstOrInit() (*model.Confession, error)
	FirstOrCreate() (*model.Confession, error)
	FindByPage(offset int, limit int) (result []*model.Confession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConfessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c confessionDo) Debug() IConfessionDo {
	return c.withDO(c.DO.Debug())
}

func (c confessionDo) WithContext(ctx context.Context) IConfessionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c confessionDo) ReadDB() IConfessionDo {
	return c.Clauses(dbresolver.Read)
}

func (c confessionDo) WriteDB() IConfessionDo {
	return c.Clauses(dbresolver.Write)
}

func (c confessionDo) Session(config *gorm.Session) IConfessionDo {
	return c.withDO(c.DO.Session(config))
}

func (c confessionDo) Clauses(conds ...clause.Expression) IConfessionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c confessionDo) Returning(value interface{}, columns ...string) IConfessionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c confessionDo) Not(conds ...gen.Condition) IConfessionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c confessionDo) Or(conds ...gen.Condition) IConfessionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c confessionDo) Select(conds ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c confessionDo) Where(conds ...gen.Condition) IConfessionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c confessionDo) Order(conds ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c confessionDo) Distinct(cols ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c confessionDo) Omit(cols ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c confessionDo) Join(table schema.Tabler, on ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c confessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c confessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c confessionDo) Group(cols ...field.Expr) IConfessionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c confessionDo) Having(conds ...gen.Condition) IConfessionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c confessionDo) Limit(limit int) IConfessionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c confessionDo) Offset(offset int) IConfessionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c confessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConfessionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c confessionDo) Unscoped() IConfessionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c confessionDo) Create(values ...*model.Confession) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c confessionDo) CreateInBatches(values []*model.Confession, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c confessionDo) Save(values ...*model.Confession) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c confessionDo) First() (*model.Confession, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Confession), nil
	}
}

func (c confessionDo) Take() (*model.Confession, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Confession), nil
	}
}

func (c confessionDo) Last() (*model.Confession, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Confession), nil
	}
}

func (c confessionDo) Find() ([]*model.Confession, error) {
	result, err := c.DO.Find()
	return result.([]*model.Confession), err
}

func (c confessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Confession, err error) {
	buf := make([]*model.Confession, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c confessionDo) FindInBatches(result *[]*model.Confession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c confessionDo) Attrs(attrs ...field.AssignExpr) IConfessionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c confessionDo) Assign(attrs ...field.AssignExpr) IConfessionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c confessionDo) Joins(fields ...field.RelationField) IConfessionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c confessionDo) Preload(fields ...field.RelationField) IConfessionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c confessionDo) FirstOrInit() (*model.Confession, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Confession), nil
	}
}

func (c confessionDo) FirstOrCreate() (*model.Confession, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Confession), nil
	}
}

func (c confessionDo) FindByPage(offset int, limit int) (result []*model.Confession, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c confessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c confessionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c confessionDo) Delete(models ...*model.Confession) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *confessionDo) withDO(do gen.Dao) *confessionDo {
	c.DO = *do.(*gen.DO)
	return c
}
