// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlock = "block"

// Block mapped from table <block>
type Block struct {
	UserID    int64 `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`           // 用户ID
	BlockedID int64 `gorm:"column:blocked_id;not null;comment:被拉黑的用户ID" json:"blocked_id"` // 被拉黑的用户ID
	BaseModel `json:"-"`
}

// TableName Block's table name
func (*Block) TableName() string {
	return TableNameBlock
}
