// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID           int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConfessionID int64                 `gorm:"column:confession_id;comment:表白帖子id" json:"confession_id"`                               // 表白帖子id
	UserID       int64                 `gorm:"column:user_id;not null;comment:评论者ID" json:"user_id"`                                   // 评论者ID
	Content      string                `gorm:"column:content;not null;comment:评论内容" json:"content"`                                    // 评论内容
	ParentID     int64                 `gorm:"column:parent_id;comment:父评论ID" json:"parent_id"`                                        // 父评论ID
	CreatedAt    time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time             `gorm:"column:updated_at;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"`          // 更新时间
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:删除时间(软删除);softDelete:milli" json:"-"`                 // 删除时间(软删除)
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
