// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	PostID    int64  `gorm:"column:post_id;comment:帖子id" json:"post_id"`           // 帖子id
	UserID    int64  `gorm:"column:user_id;not null;comment:评论者ID" json:"user_id"` // 评论者ID
	Content   string `gorm:"column:content;not null;comment:评论内容" json:"content"`  // 评论内容
	ParentID  int64  `gorm:"column:parent_id;comment:父评论ID" json:"parent_id"`      // 父评论ID
	IsDeleted bool   `gorm:"column:is_deleted;not null" json:"is_deleted"`
	BaseModel `json:"-"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
