// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePost = "post"

// Post mapped from table <post>
type Post struct {
	UserID    int64  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"` // 用户ID
	Content   string `gorm:"column:content;not null;comment:内容" json:"content"`   // 内容
	IsDeleted int8   `gorm:"column:is_deleted;not null" json:"is_deleted"`
	ImageUrls string `gorm:"column:image_urls;not null;comment:图片路径" json:"image_urls"` // 图片路径
	BaseModel `json:"-"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
