// Code generated by "gbc codegen". DO NOT EDIT.

//go:build !gbc_generate_exclude

package generate

import (
	"github.com/zjutjh/mygo/kit"
	"github.com/zjutjh/mygo/swagger"

	"app/comm"
)

func init() {
	// api/health.go:57
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeThirdServiceError,
			comm.CodeParameterInvalid,
			comm.CodeDataParseError,
			comm.CodeTooFrequently,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api.hfHealth", statusCodes)
	}

	// api/upload_image.go:85
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeParameterInvalid,
			comm.CodeSaveError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api.hfUploadImage", statusCodes)
	}

	// api/block/create.go:82
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeSearchError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/block.hfCreate", statusCodes)
	}

	// api/block/get_list.go:89
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/block.hfGetList", statusCodes)
	}

	// api/block/unblock.go:78
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeBlockExisted,
			comm.CodeBlockNotExisted,
			comm.CodeUnblockError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/block.hfUnblock", statusCodes)
	}

	// api/comment/create.go:90
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeConfessionNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/comment.hfCreate", statusCodes)
	}

	// api/comment/delete.go:88
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeCommentNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/comment.hfDelete", statusCodes)
	}

	// api/comment/get_list.go:212
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/comment.hfGetList", statusCodes)
	}

	// api/confession/create.go:100
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeOutOfLimited,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/confession.hfCreate", statusCodes)
	}

	// api/confession/delete.go:77
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/confession.hfDelete", statusCodes)
	}

	// api/confession/get_list.go:118
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeListError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/confession.hfGetList", statusCodes)
	}

	// api/confession/get_myList.go:104
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/confession.hfGetMyList", statusCodes)
	}

	// api/confession/update.go:126
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeUserNotFound,
			comm.CodeOutOfLimited,
			comm.CodeConfessionNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/confession.hfUpdate", statusCodes)
	}

	// api/user/login.go:83
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeMiddlewareServiceError,
			comm.CodeParameterInvalid,
			comm.CodeUserNotFound,
			comm.CodePasswordError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfLogin", statusCodes)
	}

	// api/user/register.go:97
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeMiddlewareServiceError,
			comm.CodeParameterInvalid,
			comm.CodeUserExisted,
			comm.CodeSaveError,
			comm.CodeHashError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfRegister", statusCodes)
	}

	// api/user/update.go:101
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeHashError,
			comm.CodeUserNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfUpdate", statusCodes)
	}
}
