// Code generated by "gbc codegen". DO NOT EDIT.

//go:build !gbc_generate_exclude

package generate

import (
	"github.com/zjutjh/mygo/kit"
	"github.com/zjutjh/mygo/swagger"

	"app/comm"
)

func init() {
	// api/health.go:57
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeThirdServiceError,
			comm.CodeParameterInvalid,
			comm.CodeDataParseError,
			comm.CodeTooFrequently,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api.hfHealth", statusCodes)
	}

	// api/upload_image.go:85
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeParameterInvalid,
			comm.CodeSaveError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api.hfUploadImage", statusCodes)
	}

	// api/block/create.go:82
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeSearchError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/block.hfCreate", statusCodes)
	}

	// api/block/get_list.go:86
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/block.hfGetList", statusCodes)
	}

	// api/block/unblock.go:78
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeBlockExisted,
			comm.CodeBlockNotExisted,
			comm.CodeUnblockError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/block.hfUnblock", statusCodes)
	}

	// api/user/login.go:77
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeMiddlewareServiceError,
			comm.CodeParameterInvalid,
			comm.CodeUserNotFound,
			comm.CodePasswordError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfLogin", statusCodes)
	}

	// api/user/register.go:91
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeMiddlewareServiceError,
			comm.CodeParameterInvalid,
			comm.CodeUserExisted,
			comm.CodeSaveError,
			comm.CodeHashError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfRegister", statusCodes)
	}

	// api/user/update.go:100
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeHashError,
			comm.CodeUserNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfUpdate", statusCodes)
	}
}
