// Code generated by "gbc codegen". DO NOT EDIT.

//go:build !gbc_generate_exclude

package generate

import (
	"github.com/zjutjh/mygo/kit"
	"github.com/zjutjh/mygo/swagger"

	"app/comm"
)

func init() {
	// api/health.go:57
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeThirdServiceError,
			comm.CodeParameterInvalid,
			comm.CodeDataParseError,
			comm.CodeTooFrequently,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api.hfHealth", statusCodes)
	}

	// api/upload_image.go:73
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeParameterInvalid,
			comm.CodeSaveError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api.hfUploadImage", statusCodes)
	}

	// api/confession/publish_confession.go:73
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeParameterInvalid,
			comm.CodeOutOfLimited,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/confession.hfPublishConfession", statusCodes)
	}

	// api/user/block.go:80
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeBlockExisted,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfBlock", statusCodes)
	}

	// api/user/login.go:77
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeMiddlewareServiceError,
			comm.CodeParameterInvalid,
			comm.CodeUserNotFound,
			comm.CodePasswordError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfLogin", statusCodes)
	}

	// api/user/register.go:91
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeMiddlewareServiceError,
			comm.CodeParameterInvalid,
			comm.CodeUserExisted,
			comm.CodeSaveError,
			comm.CodeHashError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfRegister", statusCodes)
	}

	// api/user/update.go:102
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeDatabaseError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeHashError,
			comm.CodeUserNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfUpdate", statusCodes)
	}
}
